/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppRegistryIndexRouteImport } from './routes/_app/registry/index'
import { Route as AppConfigIndexRouteImport } from './routes/_app/config/index'
import { Route as AppRegistryServiceNameRouteImport } from './routes/_app/registry/$serviceName'
import { Route as AppConfigCreateRouteImport } from './routes/_app/config/create'
import { Route as AppConfigGroupKeyRouteImport } from './routes/_app/config/$group.$key'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryIndexRoute = AppRegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryServiceNameRoute = AppRegistryServiceNameRouteImport.update({
  id: '/registry/$serviceName',
  path: '/registry/$serviceName',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigCreateRoute = AppConfigCreateRouteImport.update({
  id: '/config/create',
  path: '/config/create',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigGroupKeyRoute = AppConfigGroupKeyRouteImport.update({
  id: '/config/$group/$key',
  path: '/config/$group/$key',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/config/create': typeof AppConfigCreateRoute
  '/registry/$serviceName': typeof AppRegistryServiceNameRoute
  '/config/': typeof AppConfigIndexRoute
  '/registry/': typeof AppRegistryIndexRoute
  '/config/$group/$key': typeof AppConfigGroupKeyRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/config/create': typeof AppConfigCreateRoute
  '/registry/$serviceName': typeof AppRegistryServiceNameRoute
  '/config': typeof AppConfigIndexRoute
  '/registry': typeof AppRegistryIndexRoute
  '/config/$group/$key': typeof AppConfigGroupKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/config/create': typeof AppConfigCreateRoute
  '/_app/registry/$serviceName': typeof AppRegistryServiceNameRoute
  '/_app/config/': typeof AppConfigIndexRoute
  '/_app/registry/': typeof AppRegistryIndexRoute
  '/_app/config/$group/$key': typeof AppConfigGroupKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/dashboard'
    | '/login'
    | '/config/create'
    | '/registry/$serviceName'
    | '/config/'
    | '/registry/'
    | '/config/$group/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/'
    | '/dashboard'
    | '/login'
    | '/config/create'
    | '/registry/$serviceName'
    | '/config'
    | '/registry'
    | '/config/$group/$key'
  id:
    | '__root__'
    | '/404'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_app/'
    | '/_app/config/create'
    | '/_app/registry/$serviceName'
    | '/_app/config/'
    | '/_app/registry/'
    | '/_app/config/$group/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry/': {
      id: '/_app/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof AppRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/': {
      id: '/_app/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry/$serviceName': {
      id: '/_app/registry/$serviceName'
      path: '/registry/$serviceName'
      fullPath: '/registry/$serviceName'
      preLoaderRoute: typeof AppRegistryServiceNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/create': {
      id: '/_app/config/create'
      path: '/config/create'
      fullPath: '/config/create'
      preLoaderRoute: typeof AppConfigCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/$group/$key': {
      id: '/_app/config/$group/$key'
      path: '/config/$group/$key'
      fullPath: '/config/$group/$key'
      preLoaderRoute: typeof AppConfigGroupKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfigCreateRoute: typeof AppConfigCreateRoute
  AppRegistryServiceNameRoute: typeof AppRegistryServiceNameRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppRegistryIndexRoute: typeof AppRegistryIndexRoute
  AppConfigGroupKeyRoute: typeof AppConfigGroupKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfigCreateRoute: AppConfigCreateRoute,
  AppRegistryServiceNameRoute: AppRegistryServiceNameRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppRegistryIndexRoute: AppRegistryIndexRoute,
  AppConfigGroupKeyRoute: AppConfigGroupKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
