fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_prost_build::configure()
        .build_server(true)
        .build_client(true)
        .file_descriptor_set_path(
            std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap())
                .join("coord_descriptor.bin"),
        )
        .compile_protos(
            &[
                "src/proto/kv.proto",
                "src/proto/txn.proto",
                "src/proto/lease.proto",
                "src/proto/watch.proto",
                "src/proto/maintenance.proto",
                "src/proto/raft.proto",
                "src/proto/auth.proto",
                "src/proto/capability.proto",
                "src/proto/agent_api.proto",
            ],
            &["src/proto"],
        )?;
    Ok(())
}
